I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 5, in script call
    call scene_6
  File "game/script.rpy", line 265, in script
    main_character обычная1 "— Привет, мам… Да как тебе сказать.. Если честно, ужасно."
KeyError: 'name_mc'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 5, in script call
    call scene_6
  File "game/script.rpy", line 265, in script
    main_character обычная1 "— Привет, мам… Да как тебе сказать.. Если честно, ужасно."
  File "C:\Users\nasta\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\nasta\Downloads\renpy-8.1.3-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "C:\Users\nasta\Downloads\renpy-8.1.3-sdk\renpy\character.py", line 1335, in __call__
    who = self.prefix_suffix("who", self.who_prefix, who, self.who_suffix)
  File "C:\Users\nasta\Downloads\renpy-8.1.3-sdk\renpy\character.py", line 1251, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\nasta\Downloads\renpy-8.1.3-sdk\renpy\character.py", line 1231, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\nasta\Downloads\renpy-8.1.3-sdk\renpy\substitutions.py", line 278, in substitute
    s = formatter.vformat(s, (), kwargs) # type: ignore
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 165, in vformat
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 205, in _vformat
  File "C:\Users\nasta\Downloads\renpy-8.1.3-sdk\renpy\substitutions.py", line 168, in get_field
    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 270, in get_field
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 227, in get_value
KeyError: 'name_mc'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
The CodeQueen 1.0
Sat Nov 18 16:51:41 2023
